# version: '2.3'
version: '3'
services:

  discovery-service:
    build: discovery-service
    ports:
      - 8761:8761

  config-service:
    build: config-service
    ports:
      - 8888:8888

  customer-service:
    build: customer-service
    ports:
      - 9090:9090

  product-service:
    build: product-service
    ports:
      - 9091:9091

  order-service:
    build: order-service
    ports:
      - 8080:8080