server:
  port: 9091
greeting: 'This is product-service message.'

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true

# //TODO: Use docker for MongoDB
spring:
  data.mongodb:
    host: localhost
    port: 27017
    database: ms