server:
  port: 9091
greeting: 'This is product-service message.'

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    preferIpAddress: true
    ipAddress: 127.0.0.1